language: go
go:
- 1.10.x
go_import_path: github.com/zmalik/icte
install:
- go get -u github.com/golang/dep/cmd/dep
script:
- make build
after_success:
- if [ -n "$TRAVIS_TAG" ]; then make publish; fi
